### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [lindido/prj-rev-bwfs-dasmoto#4]
Good job with using comma-separated selectors for specifying properties for multiple elements. Alternatively, since the `font-family` is a universal style, you could use `body` as the selector instead.

```css
body {
  font-family: Helvetica;
}

```

https://github.com/lindido/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L1
